apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
      app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.svc.ports.port }}
      targetPort: {{ .Values.svc.ports.targetPort }}