name: Lab-Workflows
on:
  push:
    branches:
      - action
env:
  WORDING: "Lab-Workflows-Github"

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: check github environment
        run: hostname

      - name: build application
        run: echo "build for ${{ env.WORDING }}"

  deploy: 
    runs-on: self-hosted
    steps:
      - name: check github environment
        run: hostname