name: Deploy-minikube
run-name: ${{ github.actor }} lab CI/CD
on: [push]
jobs:
  Create-Docker-Image:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: git-checkout
        run: git clone https://github.com/samah603/helm.git -b minikube

      - name: docker login
        run: docker login -u smap1104 -p ${{ Secrets.DOCKER_REGISTRY }}

      - name: docker build
        run: |
          cd helm/docker
          docker build -t smap1104/github-runners:1.0.${{ gitHub.run_number }} .
          docker push smap1104/github-runners:10.0.${{ gitHub.run_number }}