name: example-flow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  Create-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        run: git clone https://github.com/samah603/6digi.git

      - name: docker login
        run: docker login -u smap1104 -p ${{ Secrets.DOCKER_REGISTRY }}

      - name: build and push image
        run: |
          cd 6digi
          docker build -t smap1104/6digi:10.0.$ {{ gitHub.run_number }} .
          docker push smap1104/6digi:10.0.$ {{ gitHub.run_number }}