name: Deploy-minikube
run-name: ${{ github.actor }} lab CI/CD
on: [push]
jobs:
  Create-Docker-Image:
    runs-on: self-hosted
    #runs-on: self-hosted
    steps:
      - name: git-checkout
        # run: git clone https://github.com/samah603/helm.git -b minikube
        run: |
          cd helm
          git pull

      - name: docker login
        run: docker login -u smap1104 -p ${{ Secrets.DOCKER_REGISTRY }}

      - name: docker build
        run: |
          cd helm/docker
          # docker build -t smap1104/github-runners:1.${{ gitHub.run_number }}.0 .
          # docker push smap1104/github-runners:1.${{ gitHub.run_number }}.0
          docker build -t smap1104/github-runners:1.0.0 .
          docker push smap1104/github-runners:1.0.0

      - name: deploy-minikube
        run: |
          cd helm
          ls -la
          # helm upgrade --install -f public-laboratory/chart/values.yaml myapp  public-laboratory/chart/ --set image=nukoolm/sample-app:github-1.0