name: Deploy-minikube
run-name: ${{ github.actor }} lab CI/CD
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        run: git clone https://github.com/samah603/random-6-digi.git

      - name: docker login
        run: docker login -u smap1104 -p ${{ Secrets.DOCKER_REGISTRY }}

      - name: docker build
        run: |
          pwd
          ls -la
          docker build -t smap1104/github-runners:1.0.0 .
          docker push smap1104/github-runners:1.0.0
          
      # - name: deployed
      #   run: |
      #    helm upgrade --install lab-github  -f /home/samatcha_h/actions-runner/_work/helm/helm/helm/values.yaml --set image=smap1104/github-runners:1.0.0
      #     cd /home/samatcha_h/actions-runner/_work & rm -rf helm

      # - name: deploy-minikube
      #   run: |
      #     cd helm
      #     ls -la
      #     helm upgrade --install -f public-laboratory/chart/values.yaml myapp  public-laboratory/chart/ --set image=nukoolm/sample-app:github-1.0
      #     helm upgrade --install -f /home/samatcha_h/actions-runner/_work/helm/helm/helm/values.yaml lab-github  /home/samatcha_h/actions-runner/_work/helm/helm/helm --set image=smap1104/github-runners:1.0.0